name: Snowflake Sql
description: Runs SQL against a Snowflake account in order to transform Buildkite into a Data Engineering pipeline orchestration tool.
author: https://github.com/carlwoodward
requirements: []
configuration:
  properties:
    account:
      type: string
    jwt:
      type: string
    path:
      type: string
    timeout:
      type: number
    database:
      type: string
    warehouse:
      type: string
    role:
      type: string
  required:
    - account
    - jwt
    - path
    - timeout
    - database
    - schema
    - warehouse
    - role
  additionalProperties: false
