name: Snowflake Sql
description: Runs SQL against a Snowflake account in order to transform Buildkite into a Data Engineering pipeline orchestration tool.
author: https://github.com/carlwoodward
requirements:
  - envsubst
configuration:
  properties:
    account:
      type: string
    jwt:
      type: string
    path:
      type: string
  required:
    - account
    - jwt
    - path
  additionalProperties: false
