#!/bin/bash
set -euo pipefail

SQL_ACCOUNT="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_ACCOUNT"
SQL_JWT="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_JWT"
SQL_PATH="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_PATH"
SQL_TIMEOUT="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_TIMEOUT"
SQL_DATABASE="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_DATABASE"
SQL_SCHEMA="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_SCHEMA"
SQL_WAREHOUSE="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_WAREHOUSE"
SQL_ROLE="$BUILDKITE_PLUGIN_SNOWFLAKE_SQL_ROLE"

SQL=$(cat ${SQL_PATH} | tr -s '\n' ' ')

JSON=$(cat <<-END
{
  "statement": "${SQL}",
  "timeout": ${SQL_TIMEOUT},
  "database": "${SQL_DATABASE}",
  "schema": "${SQL_SCHEMA}",
  "warehouse": "${SQL_WAREHOUSE}",
  "role": "${SQL_ROLE}"
}
END
)

curl -i -X POST \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${SQL_JWT}" \
    -H "Accept: application/json" \
    -H "User-Agent: myApplicationName/1.0" \
    -H "X-Snowflake-Authorization-Token-Type: KEYPAIR_JWT" \
    -d "${JSON}" \
    "https://${SQL_ACCOUNT}.snowflakecomputing.com/api/v2/statements"


buildkite-agent annotate "SQL run succesfully"
